name: ROS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ros_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: [humble]
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: tioros
          target-ros2-distro: ${{ matrix.ros_distro }}
          vcs-repo-file-url: ""
